//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace partials {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class about {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal about() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalWebDavid.App_LocalResources.about", typeof(about).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aalto University.
        /// </summary>
        public static string aaltoAlt {
            get {
                return ResourceManager.GetString("aaltoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2012 - 2013.
        /// </summary>
        public static string aaltoDate {
            get {
                return ResourceManager.GetString("aaltoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erasmus Program.
        /// </summary>
        public static string aaltoDescription {
            get {
                return ResourceManager.GetString("aaltoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/aalto.png.
        /// </summary>
        public static string aaltoImage {
            get {
                return ResourceManager.GetString("aaltoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helsinki.
        /// </summary>
        public static string aaltoPlace {
            get {
                return ResourceManager.GetString("aaltoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aalto University.
        /// </summary>
        public static string aaltoUni {
            get {
                return ResourceManager.GetString("aaltoUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abengoa.
        /// </summary>
        public static string abengoa {
            get {
                return ResourceManager.GetString("abengoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abengoa.
        /// </summary>
        public static string abengoaLabel {
            get {
                return ResourceManager.GetString("abengoaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberto Delgado.
        /// </summary>
        public static string albertoAlt {
            get {
                return ResourceManager.GetString("albertoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/people/Alberto.jpg.
        /// </summary>
        public static string albertoImage {
            get {
                return ResourceManager.GetString("albertoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have work with David during his employment at Avanade. Regarding to his work there, I would like to emphasize that he fit well into the team and learn quite fast the unusual technology which they were using for the project (ERP Projects in Dynamics AX).
        /// </summary>
        public static string albertoSay {
            get {
                return ResourceManager.GetString("albertoSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanade.
        /// </summary>
        public static string avanade {
            get {
                return ResourceManager.GetString("avanade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap.
        /// </summary>
        public static string bootstrapFrontend {
            get {
                return ResourceManager.GetString("bootstrapFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90%.
        /// </summary>
        public static string bootstrapFrontendValue {
            get {
                return ResourceManager.GetString("bootstrapFrontendValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las Palmas University.
        /// </summary>
        public static string canariasAlt {
            get {
                return ResourceManager.GetString("canariasAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2010 - 2011.
        /// </summary>
        public static string canariasDate {
            get {
                return ResourceManager.GetString("canariasDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seneca Program.
        /// </summary>
        public static string canariasDescription {
            get {
                return ResourceManager.GetString("canariasDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/canarias.png.
        /// </summary>
        public static string canariasImage {
            get {
                return ResourceManager.GetString("canariasImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canary Island.
        /// </summary>
        public static string canariasPlace {
            get {
                return ResourceManager.GetString("canariasPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las Palmas University.
        /// </summary>
        public static string canariasUni {
            get {
                return ResourceManager.GetString("canariasUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-code.
        /// </summary>
        public static string codeIcon {
            get {
                return ResourceManager.GetString("codeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Me Now.
        /// </summary>
        public static string contactButton {
            get {
                return ResourceManager.GetString("contactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        public static string csharpBackend {
            get {
                return ResourceManager.GetString("csharpBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90%.
        /// </summary>
        public static string csharpBackendValue {
            get {
                return ResourceManager.GetString("csharpBackendValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS.
        /// </summary>
        public static string cssFrontend {
            get {
                return ResourceManager.GetString("cssFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90%.
        /// </summary>
        public static string cssFrontendValue {
            get {
                return ResourceManager.GetString("cssFrontendValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daimler.
        /// </summary>
        public static string daimlerLabel {
            get {
                return ResourceManager.GetString("daimlerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February 2014 - August 2014.
        /// </summary>
        public static string dateAbengoa {
            get {
                return ResourceManager.GetString("dateAbengoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May 2015 - May 2016.
        /// </summary>
        public static string dateAvanade {
            get {
                return ResourceManager.GetString("dateAvanade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August 2014 - May 2015.
        /// </summary>
        public static string dateFreelancer {
            get {
                return ResourceManager.GetString("dateFreelancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July 2013 - January 2014.
        /// </summary>
        public static string dateSabic {
            get {
                return ResourceManager.GetString("dateSabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delfin English School.
        /// </summary>
        public static string delfinAlt {
            get {
                return ResourceManager.GetString("delfinAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011 (3 months).
        /// </summary>
        public static string delfinDate {
            get {
                return ResourceManager.GetString("delfinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English B2.
        /// </summary>
        public static string delfinDescription {
            get {
                return ResourceManager.GetString("delfinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/delfin.png.
        /// </summary>
        public static string delfinImage {
            get {
                return ResourceManager.GetString("delfinImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dublin.
        /// </summary>
        public static string delfinPlace {
            get {
                return ResourceManager.GetString("delfinPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delfin English School.
        /// </summary>
        public static string delfinUni {
            get {
                return ResourceManager.GetString("delfinUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass and energy balance calculation for both a multi-effect evaporation system and a sludge treatment system (dewatering).
        /// </summary>
        public static string descriptionAbengoa {
            get {
                return ResourceManager.GetString("descriptionAbengoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development of an ERP application (Executive Resource Planning) for an important supermarket. Other assignments: CSS, HTML, and MVC..
        /// </summary>
        public static string descriptionAvanade {
            get {
                return ResourceManager.GetString("descriptionAvanade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development/Design of webs and applications for several clients: construction company, personal profiles, and a management application for a small company.
        /// </summary>
        public static string descriptionFreelancer {
            get {
                return ResourceManager.GetString("descriptionFreelancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation and optimization of real and operating wastewater treatment plant by using a mathematical model.
        /// </summary>
        public static string descriptionSabic {
            get {
                return ResourceManager.GetString("descriptionSabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I enjoy programming, learning new things, and helping people with my projects. Scroll down to see my CV or click on:.
        /// </summary>
        public static string descriptionWhat {
            get {
                return ResourceManager.GetString("descriptionWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDUCATION.
        /// </summary>
        public static string educationHeading {
            get {
                return ResourceManager.GetString("educationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Education -&lt;/b&gt; MSc. Engineer. I attended my courses in different universities (Seville, Canary Island, Helsinki)..
        /// </summary>
        public static string educationWhat {
            get {
                return ResourceManager.GetString("educationWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Experience -&lt;/b&gt; Over two years experience in different projects (water treatment, energy, IT)..
        /// </summary>
        public static string experienceWhat {
            get {
                return ResourceManager.GetString("experienceWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsmaelAbrego.
        /// </summary>
        public static string freelancerIsmael {
            get {
                return ResourceManager.GetString("freelancerIsmael", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jmhermanos.
        /// </summary>
        public static string freelancerJmHermanos {
            get {
                return ResourceManager.GetString("freelancerJmHermanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-graduation-cap.
        /// </summary>
        public static string hatIcon {
            get {
                return ResourceManager.GetString("hatIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back-End.
        /// </summary>
        public static string headingBackend {
            get {
                return ResourceManager.GetString("headingBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front-End.
        /// </summary>
        public static string headingFrontend {
            get {
                return ResourceManager.GetString("headingFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string htmlFrontend {
            get {
                return ResourceManager.GetString("htmlFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90%.
        /// </summary>
        public static string htmlFrontendValue {
            get {
                return ResourceManager.GetString("htmlFrontendValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrego Web.
        /// </summary>
        public static string ismaelLabel {
            get {
                return ResourceManager.GetString("ismaelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jmhermanos.
        /// </summary>
        public static string jmhermanosLabel {
            get {
                return ResourceManager.GetString("jmhermanosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to José Maria Vazquez.
        /// </summary>
        public static string joseAlt {
            get {
                return ResourceManager.GetString("joseAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/people/JoseMaria.jpg.
        /// </summary>
        public static string joseImage {
            get {
                return ResourceManager.GetString("joseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have studied with David for seven years. I think he would be a good asset for any company in the IT industry since he love learning new things which is highly important in this changing sector.
        /// </summary>
        public static string josemariaSay {
            get {
                return ResourceManager.GetString("josemariaSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jquery.
        /// </summary>
        public static string jqueryFrontend {
            get {
                return ResourceManager.GetString("jqueryFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80%.
        /// </summary>
        public static string jqueryFrontendValue {
            get {
                return ResourceManager.GetString("jqueryFrontendValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberto Delgado - Developer.
        /// </summary>
        public static string linkedinAlbertoTilte {
            get {
                return ResourceManager.GetString("linkedinAlbertoTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberto&apos;s Linkedin.
        /// </summary>
        public static string linkedinAlbertoTitleShort {
            get {
                return ResourceManager.GetString("linkedinAlbertoTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://es.linkedin.com/in/albertodelgadocruzado/en.
        /// </summary>
        public static string linkedinAlbertoUrl {
            get {
                return ResourceManager.GetString("linkedinAlbertoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jose&apos;s Linkedin.
        /// </summary>
        public static string linkedinJoseShortTitle {
            get {
                return ResourceManager.GetString("linkedinJoseShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to José Maria Vázquez - Process Engineer at Yokogawa.
        /// </summary>
        public static string linkedinJoseTitle {
            get {
                return ResourceManager.GetString("linkedinJoseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://nl.linkedin.com/in/josé-maría-vázquez-jiménez-2a887768/en.
        /// </summary>
        public static string linkedinJoseUrl {
            get {
                return ResourceManager.GetString("linkedinJoseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubén Espadas - Analyst at Tecnocom.
        /// </summary>
        public static string linkedinRubenTitle {
            get {
                return ResourceManager.GetString("linkedinRubenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubén&apos;s Linkedin.
        /// </summary>
        public static string linkedinRubenTitleShort {
            get {
                return ResourceManager.GetString("linkedinRubenTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://es.linkedin.com/in/rubén-espada-bernal-ab418541/en.
        /// </summary>
        public static string linkedinRubenUrl {
            get {
                return ResourceManager.GetString("linkedinRubenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sajith&apos;s Linkedin.
        /// </summary>
        public static string linkedinSagitShortTitle {
            get {
                return ResourceManager.GetString("linkedinSagitShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sajith Mohideen - Process Engineer at Fabricom Engie.
        /// </summary>
        public static string linkedinSagitTitle {
            get {
                return ResourceManager.GetString("linkedinSagitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://uk.linkedin.com/in/sajith-mohideen-b3270b47.
        /// </summary>
        public static string linkedinSagitUrl {
            get {
                return ResourceManager.GetString("linkedinSagitUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Where have I studied?.
        /// </summary>
        public static string mapAlt {
            get {
                return ResourceManager.GetString("mapAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/mapCircleTiny.png.
        /// </summary>
        public static string mapCircleImage {
            get {
                return ResourceManager.GetString("mapCircleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/mapSquareTiny.png.
        /// </summary>
        public static string mapSquareImage {
            get {
                return ResourceManager.GetString("mapSquareImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVC.
        /// </summary>
        public static string mvcBackend {
            get {
                return ResourceManager.GetString("mvcBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80%.
        /// </summary>
        public static string mvcBackendValue {
            get {
                return ResourceManager.GetString("mvcBackendValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion Docs.
        /// </summary>
        public static string mvcLabel {
            get {
                return ResourceManager.GetString("mvcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB.
        /// </summary>
        public static string netBackend {
            get {
                return ResourceManager.GetString("netBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70%.
        /// </summary>
        public static string netBackendValue {
            get {
                return ResourceManager.GetString("netBackendValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David thinking.
        /// </summary>
        public static string pensamientoAlt {
            get {
                return ResourceManager.GetString("pensamientoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/pensamientoTiny.png.
        /// </summary>
        public static string pensamientoImage {
            get {
                return ResourceManager.GetString("pensamientoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What my coworkers say about me?.
        /// </summary>
        public static string peopleHeading {
            get {
                return ResourceManager.GetString("peopleHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;¿What my coworkers say about me? -&lt;/b&gt; Have a look at the opinions of my coworkers..
        /// </summary>
        public static string peopleWhat {
            get {
                return ResourceManager.GetString("peopleWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photoshop.
        /// </summary>
        public static string photoshopFrontend {
            get {
                return ResourceManager.GetString("photoshopFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70%.
        /// </summary>
        public static string photoshopFrontendValue {
            get {
                return ResourceManager.GetString("photoshopFrontendValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior Engineer.
        /// </summary>
        public static string positionAbengoa {
            get {
                return ResourceManager.GetString("positionAbengoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string positionAvanade {
            get {
                return ResourceManager.GetString("positionAvanade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freelancer.
        /// </summary>
        public static string positionFreelancer {
            get {
                return ResourceManager.GetString("positionFreelancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internship.
        /// </summary>
        public static string positionSabic {
            get {
                return ResourceManager.GetString("positionSabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubén Espadas.
        /// </summary>
        public static string rubenAlt {
            get {
                return ResourceManager.GetString("rubenAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/people/ruben.jpg.
        /// </summary>
        public static string rubenImage {
            get {
                return ResourceManager.GetString("rubenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David and I worked together in several freelance projects few years ago. Although at that time he was learning in an autodidactic way about  web applications and coding, his little experience was not a drawback and he performed all the assignments as if he were a senior developer.
        /// </summary>
        public static string rubenSay {
            get {
                return ResourceManager.GetString("rubenSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabic.
        /// </summary>
        public static string sabic {
            get {
                return ResourceManager.GetString("sabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabic.
        /// </summary>
        public static string sabicLabel {
            get {
                return ResourceManager.GetString("sabicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sajith Mohideen.
        /// </summary>
        public static string sajithAlt {
            get {
                return ResourceManager.GetString("sajithAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/people/Sajit.jpg.
        /// </summary>
        public static string sajithImage {
            get {
                return ResourceManager.GetString("sajithImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David was my co-worker and roommate during my employment at Sabic (The netherlands).  During the period in which we work together I was able to observe how hard working and professional he is. His project, which was complex and has a tight deadline, was performed within the planned timeframe  and to a high standard.
        /// </summary>
        public static string sajithSay {
            get {
                return ResourceManager.GetString("sajithSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seville University.
        /// </summary>
        public static string sevillaAlt {
            get {
                return ResourceManager.GetString("sevillaAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2006 - 2013.
        /// </summary>
        public static string sevillaDate {
            get {
                return ResourceManager.GetString("sevillaDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Engineering.
        /// </summary>
        public static string sevillaDescription {
            get {
                return ResourceManager.GetString("sevillaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/sevilla.png.
        /// </summary>
        public static string sevillaImage {
            get {
                return ResourceManager.GetString("sevillaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seville.
        /// </summary>
        public static string sevillaPlace {
            get {
                return ResourceManager.GetString("sevillaPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seville University.
        /// </summary>
        public static string sevillaUni {
            get {
                return ResourceManager.GetString("sevillaUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY SKILLS.
        /// </summary>
        public static string skillHeading {
            get {
                return ResourceManager.GetString("skillHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Skills -&lt;/b&gt; I have both knowledge and experience in C#, MVC, Jquery, SQL....and more..
        /// </summary>
        public static string skillsWhat {
            get {
                return ResourceManager.GetString("skillsWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server.
        /// </summary>
        public static string sqlBackend {
            get {
                return ResourceManager.GetString("sqlBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70%.
        /// </summary>
        public static string sqlBackendValue {
            get {
                return ResourceManager.GetString("sqlBackendValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-suitcase.
        /// </summary>
        public static string suitCaseIcon {
            get {
                return ResourceManager.GetString("suitCaseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supeco.
        /// </summary>
        public static string supecoLabel {
            get {
                return ResourceManager.GetString("supecoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-users.
        /// </summary>
        public static string usersIcon {
            get {
                return ResourceManager.GetString("usersIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Forms.
        /// </summary>
        public static string webBackend {
            get {
                return ResourceManager.GetString("webBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70%.
        /// </summary>
        public static string webBackendValue {
            get {
                return ResourceManager.GetString("webBackendValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string whatAboutHeading {
            get {
                return ResourceManager.GetString("whatAboutHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERIENCE.
        /// </summary>
        public static string workHeading {
            get {
                return ResourceManager.GetString("workHeading", resourceCulture);
            }
        }
    }
}
