//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace partials {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalWebDavid.App_LocalResources.index", typeof(index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abengoa.
        /// </summary>
        public static string abengoaAlt {
            get {
                return ResourceManager.GetString("abengoaAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/companies/Abengoa300.jpg.
        /// </summary>
        public static string abengoaImage {
            get {
                return ResourceManager.GetString("abengoaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More About Me.
        /// </summary>
        public static string aboutButton {
            get {
                return ResourceManager.GetString("aboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-paper-plane-o.
        /// </summary>
        public static string aboutIcon {
            get {
                return ResourceManager.GetString("aboutIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All.
        /// </summary>
        public static string allButton {
            get {
                return ResourceManager.GetString("allButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK-END PART.
        /// </summary>
        public static string backEnd {
            get {
                return ResourceManager.GetString("backEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-code.
        /// </summary>
        public static string backEndIcon {
            get {
                return ResourceManager.GetString("backEndIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET, MVC, C#, EF, SQL Server....
        /// </summary>
        public static string backEndText {
            get {
                return ResourceManager.GetString("backEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download CV.
        /// </summary>
        public static string downloadButton {
            get {
                return ResourceManager.GetString("downloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-cloud-download.
        /// </summary>
        public static string downloadIcon {
            get {
                return ResourceManager.GetString("downloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRONT-END PART.
        /// </summary>
        public static string frontEnd {
            get {
                return ResourceManager.GetString("frontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-html5.
        /// </summary>
        public static string frontEndIcon {
            get {
                return ResourceManager.GetString("frontEndIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML, CSS, Jquery, Bootstrap, Responsive....
        /// </summary>
        public static string frontEndText {
            get {
                return ResourceManager.GetString("frontEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daimler-Mercedes.
        /// </summary>
        public static string mercedesAlt {
            get {
                return ResourceManager.GetString("mercedesAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/companies/mercedes300.jpg.
        /// </summary>
        public static string mercedesImage {
            get {
                return ResourceManager.GetString("mercedesImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAVID ALCOCER.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a .NET developer with over 2 years experience, and with a good knowledge of both front-end and web design..
        /// </summary>
        public static string nameDescription {
            get {
                return ResourceManager.GetString("nameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Developer.
        /// </summary>
        public static string nameSubHeading {
            get {
                return ResourceManager.GetString("nameSubHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Alcocer .Net Developer.
        /// </summary>
        public static string pictureAlt {
            get {
                return ResourceManager.GetString("pictureAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen Profile David.
        /// </summary>
        public static string pizarraAlt {
            get {
                return ResourceManager.GetString("pizarraAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/pizarraWhite45.png.
        /// </summary>
        public static string pizarraImage {
            get {
                return ResourceManager.GetString("pizarraImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have been lucky enough to participate in different projects for companies in the chemical, renewal, and IT industry.
        /// </summary>
        public static string pojectSummaryDescription {
            get {
                return ResourceManager.GetString("pojectSummaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY WORK.
        /// </summary>
        public static string projectSummaryTitle {
            get {
                return ResourceManager.GetString("projectSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabic.
        /// </summary>
        public static string sabicAlt {
            get {
                return ResourceManager.GetString("sabicAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/companies/sabic300.jpg.
        /// </summary>
        public static string sabicImage {
            get {
                return ResourceManager.GetString("sabicImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supeco.
        /// </summary>
        public static string supecoAlt {
            get {
                return ResourceManager.GetString("supecoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/companies/supeco300.jpg.
        /// </summary>
        public static string supecoImage {
            get {
                return ResourceManager.GetString("supecoImage", resourceCulture);
            }
        }
    }
}
