//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace partials {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class layoutRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal layoutRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalWebDavid.App_LocalResources.layoutRes", typeof(layoutRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abengoa.
        /// </summary>
        public static string abengoa {
            get {
                return ResourceManager.GetString("abengoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me/CV.
        /// </summary>
        public static string aboutMenu {
            get {
                return ResourceManager.GetString("aboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Me.
        /// </summary>
        public static string addFooter {
            get {
                return ResourceManager.GetString("addFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs Management.
        /// </summary>
        public static string avalibrary {
            get {
                return ResourceManager.GetString("avalibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string blogMenu {
            get {
                return ResourceManager.GetString("blogMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string compartir {
            get {
                return ResourceManager.GetString("compartir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string connectFooter {
            get {
                return ResourceManager.GetString("connectFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contactFooter {
            get {
                return ResourceManager.GetString("contactFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contactoMenu {
            get {
                return ResourceManager.GetString("contactoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download CV.
        /// </summary>
        public static string downloadFooter {
            get {
                return ResourceManager.GetString("downloadFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-download.
        /// </summary>
        public static string downloadIcon {
            get {
                return ResourceManager.GetString("downloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string experience {
            get {
                return ResourceManager.GetString("experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-facebook-f.
        /// </summary>
        public static string facebookIcon {
            get {
                return ResourceManager.GetString("facebookIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/footerTiny.png.
        /// </summary>
        public static string footerImage {
            get {
                return ResourceManager.GetString("footerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAVID ALCOCER.
        /// </summary>
        public static string footerImageAlt {
            get {
                return ResourceManager.GetString("footerImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google+.
        /// </summary>
        public static string google {
            get {
                return ResourceManager.GetString("google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Up.
        /// </summary>
        public static string goUpButton {
            get {
                return ResourceManager.GetString("goUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jmhermanos.
        /// </summary>
        public static string jmhermanos {
            get {
                return ResourceManager.GetString("jmhermanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedin.
        /// </summary>
        public static string linkedin {
            get {
                return ResourceManager.GetString("linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-linkedin.
        /// </summary>
        public static string linkedinIcon {
            get {
                return ResourceManager.GetString("linkedinIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAVIDALCOCER.COM -.
        /// </summary>
        public static string logoFooter {
            get {
                return ResourceManager.GetString("logoFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCOCER.COM.
        /// </summary>
        public static string logoMobileAlcocer {
            get {
                return ResourceManager.GetString("logoMobileAlcocer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAVID.
        /// </summary>
        public static string logoMobileDavid {
            get {
                return ResourceManager.GetString("logoMobileDavid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAVIDALCOCER.COM.
        /// </summary>
        public static string logoName {
            get {
                return ResourceManager.GetString("logoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercedes-Daimler.
        /// </summary>
        public static string mercedes {
            get {
                return ResourceManager.GetString("mercedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016 Informative Page.
        /// </summary>
        public static string pageInfo {
            get {
                return ResourceManager.GetString("pageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What people say about me?.
        /// </summary>
        public static string peopleSay {
            get {
                return ResourceManager.GetString("peopleSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-volume-control-phone.
        /// </summary>
        public static string phoneIcon {
            get {
                return ResourceManager.GetString("phoneIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string projectsMenu {
            get {
                return ResourceManager.GetString("projectsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabic.
        /// </summary>
        public static string sabic {
            get {
                return ResourceManager.GetString("sabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string shareText {
            get {
                return ResourceManager.GetString("shareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Skills.
        /// </summary>
        public static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to España.
        /// </summary>
        public static string spain {
            get {
                return ResourceManager.GetString("spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/es.svg.
        /// </summary>
        public static string spainImage {
            get {
                return ResourceManager.GetString("spainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supeco.
        /// </summary>
        public static string supeco {
            get {
                return ResourceManager.GetString("supeco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - DAVIDALCOCER.COM.
        /// </summary>
        public static string titleMainConGuion {
            get {
                return ResourceManager.GetString("titleMainConGuion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAVIDALCOCER.COM.
        /// </summary>
        public static string titleMainSinGuion {
            get {
                return ResourceManager.GetString("titleMainSinGuion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twiter.
        /// </summary>
        public static string twiter {
            get {
                return ResourceManager.GetString("twiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string uk {
            get {
                return ResourceManager.GetString("uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/gb.svg.
        /// </summary>
        public static string ukImage {
            get {
                return ResourceManager.GetString("ukImage", resourceCulture);
            }
        }
    }
}
