//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace partials {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class projects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal projects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalWebDavid.App_LocalResources.projects", typeof(projects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abengoa.
        /// </summary>
        public static string abengoaAlt {
            get {
                return ResourceManager.GetString("abengoaAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/companies/Abengoa300.jpg.
        /// </summary>
        public static string abengoaSmall {
            get {
                return ResourceManager.GetString("abengoaSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M&amp;E Balance calculation for a waste treatment system.
        /// </summary>
        public static string abengoaThumb {
            get {
                return ResourceManager.GetString("abengoaThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs Management.
        /// </summary>
        public static string avalibraryAlt {
            get {
                return ResourceManager.GetString("avalibraryAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/companies/avanadeLibrary300.jpg.
        /// </summary>
        public static string avalibrarySmall {
            get {
                return ResourceManager.GetString("avalibrarySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management application developed in MVC.
        /// </summary>
        public static string avalibraryThumb {
            get {
                return ResourceManager.GetString("avalibraryThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JmHermanos.
        /// </summary>
        public static string jmhermanosAlt {
            get {
                return ResourceManager.GetString("jmhermanosAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/companies/jmhermanos300.jpg.
        /// </summary>
        public static string jmhermanosSmall {
            get {
                return ResourceManager.GetString("jmhermanosSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web and Blog for a construction company.
        /// </summary>
        public static string jmhermanosThumb {
            get {
                return ResourceManager.GetString("jmhermanosThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daimler-Mercedes.
        /// </summary>
        public static string mercedesAlt {
            get {
                return ResourceManager.GetString("mercedesAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/companies/mercedes300.jpg.
        /// </summary>
        public static string mercedesSmall {
            get {
                return ResourceManager.GetString("mercedesSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance of a SharePoint intranet.
        /// </summary>
        public static string mercedesThumb {
            get {
                return ResourceManager.GetString("mercedesThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string moreButton {
            get {
                return ResourceManager.GetString("moreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string projectHeading {
            get {
                return ResourceManager.GetString("projectHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a look at some of my projects.
        /// </summary>
        public static string projectSays {
            get {
                return ResourceManager.GetString("projectSays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Projects.
        /// </summary>
        public static string risaAlt {
            get {
                return ResourceManager.GetString("risaAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/risaCorteTiny.png.
        /// </summary>
        public static string risaImage {
            get {
                return ResourceManager.GetString("risaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabic.
        /// </summary>
        public static string sabicAlt {
            get {
                return ResourceManager.GetString("sabicAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/companies/sabic300.jpg.
        /// </summary>
        public static string sabicSmall {
            get {
                return ResourceManager.GetString("sabicSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wastewater treatment plant optimization.
        /// </summary>
        public static string sabicThumb {
            get {
                return ResourceManager.GetString("sabicThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supeco.
        /// </summary>
        public static string supecoAlt {
            get {
                return ResourceManager.GetString("supecoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/companies/supeco300.jpg.
        /// </summary>
        public static string supecoSmall {
            get {
                return ResourceManager.GetString("supecoSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development of a ERP for a supermarket.
        /// </summary>
        public static string supecoThumb {
            get {
                return ResourceManager.GetString("supecoThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Projects.
        /// </summary>
        public static string titleWithGuion {
            get {
                return ResourceManager.GetString("titleWithGuion", resourceCulture);
            }
        }
    }
}
