//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace url {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class url {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal url() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalWebDavid.App_GlobalResources.url", typeof(url).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abengoa.
        /// </summary>
        public static string abengoaSection2 {
            get {
                return ResourceManager.GetString("abengoaSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.abengoabioenergy.com/web/es/index.html.
        /// </summary>
        public static string abengoaUrl {
            get {
                return ResourceManager.GetString("abengoaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string aboutSection {
            get {
                return ResourceManager.GetString("aboutSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc-management.
        /// </summary>
        public static string avalibrarySection2 {
            get {
                return ResourceManager.GetString("avalibrarySection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.avanade.com/en-gb.
        /// </summary>
        public static string avanadeUrl {
            get {
                return ResourceManager.GetString("avanadeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog.
        /// </summary>
        public static string blogSection {
            get {
                return ResourceManager.GetString("blogSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string contactSection {
            get {
                return ResourceManager.GetString("contactSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download-cv.
        /// </summary>
        public static string cvPage {
            get {
                return ResourceManager.GetString("cvPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://doc-management.davidalcocer.com/.
        /// </summary>
        public static string docsUrl {
            get {
                return ResourceManager.GetString("docsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Data/(English)-DavidAlcocer-CV.doc.
        /// </summary>
        public static string downloadCvEn {
            get {
                return ResourceManager.GetString("downloadCvEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Data/DavidAlcocer-CV.doc.
        /// </summary>
        public static string downloadCVEs {
            get {
                return ResourceManager.GetString("downloadCVEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my-education.
        /// </summary>
        public static string educationId {
            get {
                return ResourceManager.GetString("educationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my-experience.
        /// </summary>
        public static string experienceId {
            get {
                return ResourceManager.GetString("experienceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string homeSection {
            get {
                return ResourceManager.GetString("homeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.ismaelabrego.com/.
        /// </summary>
        public static string ismaelUrl {
            get {
                return ResourceManager.GetString("ismaelUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jmhermanos.
        /// </summary>
        public static string jmhermanosSection2 {
            get {
                return ResourceManager.GetString("jmhermanosSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.jmhermanos.es/.
        /// </summary>
        public static string jmhermanosUrl {
            get {
                return ResourceManager.GetString("jmhermanosUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daimler.
        /// </summary>
        public static string mercedesSection2 {
            get {
                return ResourceManager.GetString("mercedesSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #messagesBox.
        /// </summary>
        public static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/ingmoyete.
        /// </summary>
        public static string myFacebook {
            get {
                return ResourceManager.GetString("myFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://es.linkedin.com/in/david-alcocer-palma-a38b4467.
        /// </summary>
        public static string myLinkedin {
            get {
                return ResourceManager.GetString("myLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what-people-say.
        /// </summary>
        public static string peopleId {
            get {
                return ResourceManager.GetString("peopleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        public static string projectsSection {
            get {
                return ResourceManager.GetString("projectsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thumbnails.
        /// </summary>
        public static string projectsThumb {
            get {
                return ResourceManager.GetString("projectsThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sabic.
        /// </summary>
        public static string sabicSection2 {
            get {
                return ResourceManager.GetString("sabicSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.sabic-ip.com/gep/en/Home/Home/home.html.
        /// </summary>
        public static string sabicUrl {
            get {
                return ResourceManager.GetString("sabicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my-skills.
        /// </summary>
        public static string skillsId {
            get {
                return ResourceManager.GetString("skillsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supeco.
        /// </summary>
        public static string supecoSection2 {
            get {
                return ResourceManager.GetString("supecoSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to summary.
        /// </summary>
        public static string whatAbout {
            get {
                return ResourceManager.GetString("whatAbout", resourceCulture);
            }
        }
    }
}
